# Generated by Django 2.2.1 on 2019-06-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fivequiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('photo', models.ImageField(upload_to='word/photo_5')),
            ],
        ),
        migrations.CreateModel(
            name='Fourquiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
                ('photo', models.ImageField(upload_to='word/photo_4')),
            ],
        ),
        migrations.CreateModel(
            name='Threequiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
                ('photo', models.ImageField(upload_to='word/photo_3')),
            ],
        ),
    ]
