# Generated by Django 2.2.1 on 2019-06-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordquiz', '0003_auto_20190604_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='fivequiz',
            name='tag',
            field=models.IntegerField(default=int),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fourquiz',
            name='tag',
            field=models.IntegerField(default=int),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fivequiz',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fourquiz',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='threequiz',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
