# Generated by Django 2.2.1 on 2019-06-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordquiz', '0005_remove_threequiz_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='threequiz',
            name='name',
            field=models.CharField(default=str, max_length=100),
            preserve_default=False,
        ),
    ]
