# Generated by Django 2.2.1 on 2019-06-18 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordquiz', '0007_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Level',
        ),
    ]
